### ISSUE TITLE
Not working in High Sierra?

### ISSUE THREAD

**Issue by pugson** [ramiroaraujo/alfred-set-resolution-workflow#5]
```
ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pugson/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.D150609C-1D5E-41B4-B1C3-6428CEAF34A4/workflow_config.rb:2:in `<top (required)>'
	from ./feedback.rb:5:in `require_relative'
	from ./feedback.rb:5:in `<main>'
```

Nothing happens when I type in `setresolution` and the error above appears in Alfred's console.

**Comment by pugson** [comment]
Fixed with these steps:
- `bundle install` inside the Alfred workflow folder
- `/usr/bin/gem install alfred-workflow`
