### ISSUE TITLE
doesn't work with mac os sierra

### ISSUE THREAD

**Issue by jitrulz** [ramiroaraujo/alfred-set-resolution-workflow#6]
doesn't show list of resolutions.

**Comment by AaronHolbrook** [comment]
Same

**Comment by AaronHolbrook** [comment]
As I type it shows:

![](http://d.pr/i/BtoXOm/4wad6MQN+)

Then once I get to the normal position it then shows as if it's a search:

![](http://d.pr/i/ltgiv3/2mdODej6+)

**Comment by AaronHolbrook** [comment]
Debugging info: 

![](http://d.pr/i/bVDX3F/3uz3R8XN+)

**Comment by luinhon** [comment]
I fix this problem, and create pull request about this.

If you want temporary fixed version, you can download here.

https://github.com/luinhon/alfred-set-resolution-workflow/raw/master/alfred-set-resolution.alfredworkflow

**Comment by sebsel** [comment]
I had this too, and with a few other workflows as well. Turns out it's related to macOS's default ruby, which has changed.

For me it worked to open the workflow, double click on the first step to open the settings, click on the button (1) to open the workflow's folder in Finder and change the ruby version in the `bundle/ruby` subfolder (2) from `2.0.0` to `2.3.0`.

![schermafbeelding 2018-06-16 om 10 31 36](https://user-images.githubusercontent.com/16517999/41497217-46fc9444-7151-11e8-8393-d73f1568e516.jpg)

**Comment by AdamBD** [comment]
`[08:59:58.156] ERROR: Set Resolution[Script Filter] Code 1: /Users/abd/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CAC029B5-ADD5-45E9-89AD-01299B53E93C/bundle/ruby/2.6.0/gems/builder-3.2.2/lib/builder/xchar.rb:111: warning: constant ::Fixnum is deprecated
/Users/abd/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CAC029B5-ADD5-45E9-89AD-01299B53E93C/workflow_config.rb:66:in `rebuild_resolutions': undefined method `each_with_index' for nil:NilClass (NoMethodError)
	from /Users/abd/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CAC029B5-ADD5-45E9-89AD-01299B53E93C/workflow_config.rb:57:in `load_display_resolutions'
	from /Users/abd/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.CAC029B5-ADD5-45E9-89AD-01299B53E93C/workflow_config.rb:13:in `initialize'
	from ./feedback.rb:11:in `new'
	from ./feedback.rb:11:in `<main>'`

Any ideas?

**Comment by youtextme** [comment]
If you’re stuck on “doesn't work with mac os sierra”: dual-hotkey trial beats waiting on a broken/missing Alfred workflow — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack or Raycast Pro after clipboard/file actions prove weekly value.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
